### ISSUE TITLE
"Empty begin statement" issue is not generated properly for several empty procedures in a row

### ISSUE THREAD

**Issue by Teloah** [fabriciocolombo/sonar-delphi#13]
"Empty begin statement" issue will be generated only for procedures `One`, `Three` and `Five`.

``` delphi
unit EmptyProcs;

interface

type
  TEmptyProcs = class
  public
    procedure One;
    procedure Two;
    procedure Three;
    procedure Four;
    procedure Five;
  end;

implementation

procedure TEmptyProcs.One;
begin

end;

procedure TEmptyProcs.Two;
begin

end;

procedure TEmptyProcs.Three;
begin

end;

procedure TEmptyProcs.Four;
begin

end;

procedure TEmptyProcs.Five;
begin

end;

end.
```

**Comment by fabriciocolombo** [comment]
Thank you for reporting the error.

Should be a problem with the XPath expression evaluation. The expression seems be OK.
https://github.com/fabriciocolombo/sonar-delphi/blob/master/src/main/resources/org/sonar/plugins/delphi/pmd/rules.xml#L356

This [gist](https://gist.github.com/3130a783d1ccd5dd4442.git) contains the generated AST. I tested the XPath expression (here)[http://www.freeformatter.com/xpath-tester.html) and it returns five nodes correctly, which leads me to believe that the problem is in [XPathRule](https://github.com/fabriciocolombo/sonar-delphi/blob/master/src/main/java/org/sonar/plugins/delphi/pmd/rules/XPathRule.java) class.

I will rewrite this rule to java code. The [XPathRule code](https://github.com/fabriciocolombo/sonar-delphi/blob/master/src/main/java/org/sonar/plugins/delphi/pmd/rules/XPathRule.java) it's very weird.
